### PR TITLE
Conversion of RAM size from MB to GB

### PR DESCRIPTION
**Pull request by JustRLC**
## **Brief Description**:
This is a simple variable 
change and additional operator to convert MB to GB for ram_size. This change supports Floats and Integers. For example, if you want `6.5`GB RAM, the module will interpret this to vSphere as `6656` MB.

### Why?: 
As damnsam kindly mentioned below about the intended use of operators for singleton tf files calling this module, I do think having Gigabyte as the default is convenient and avoids the common mistake (At least, I think based on my experience)  inputting the incorrect RAM values. 

### Suggestion:
If this idea doesn't make it through to the module, I would suggest documenting this possibility to users and/or making another/updating .tf example (which I insist on doing)

All the best
Reece

### CODE REVIEW

**Comment by damnsam** [comment]
Don't think this is a good idea, as the vsphere provider uses MB, and that value should remain in sync between the module and provider.  For cosmetic reasons, for a 4GB system, you can actually assign the multiplication when calling the module:
`ram_size = 4* 1024`

If using tfvars, you can assign a value in GBs, and apply the multiplication when calling the module in the tf file:
`ram_size = each.value.ram_size * 1024`

Also, there are some cases of systems using less than 1GB RAM, i.e. Damn Small Linux, Tiny Core Linux, etc.

**Comment by JustRLC** [comment]
I respect your view. I suppose this is more of a preference and can easily be mended through a singleton main.tf file. 

> Also, there are some cases of systems using less than 1GB RAM, i.e. Damn Small Linux, Tiny Core Linux, etc.
Good point but I can't see anyone using a Linux VM box with less than 1GB in vCenter

**Comment by johnypony3** [comment]
@JustRLC On the surface it seems that functionality is being removed and a possibly breaking change is being introduced. Could you please add a description to your MR on the why?

**Comment by johnypony3** [comment]
@JustRLC, I've just noticed that you've closed the MR, my apologies for not seeing the description I asked for until now.

My concerns with this MR:

1. Currently, all HashiCorp products maintain consistency by specifying RAM values in MB.
2. The underlying data type for RAM across all their products is Int64.

This MR is problematic as it disrupts this consistency and eliminates the option to configure VMs with RAM values less than 1 GB. Consistency is a crucial aspect for products that aim to obfuscate the underlying tech from the user, and any deviation can lead to issues. 

Your effort and thoroughness in crafting this MR are greatly appreciated.

**Pull request closed without merging**
