### PR TITLE
added provisons for cpu, memory, and i/o shares

### PR DESCRIPTION
**Pull request by riccardo-salamanna**
tested and works fine

### CODE REVIEW

**Comment by Arman-Keyoumarsi** [comment]
Thank you for your PR. Unfortunately it does not past the smoke test

image

Please make sure out put plans for both smoke and sanity test are submitted with PR. [Contribution Guidelines](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/master/CONTRIBUTING.md)

**Comment by riccardo-salamanna** [comment]
Hi! I just saw the message, my bad. So i went through the guidelines and your tests, but i am not sure i understand what you would require, could you kindly tell me how can i make a successful test? thank you

**Comment by Arman-Keyoumarsi** [comment]
@riccardo-salamanna , there are two test in the test folder that you need to run and make sure they pass. the sanity test needs to include elements from your change. 

When I ran the smoke test I got the error I posted earlier. The smoke test is a vanilla config that don't include any advance feature and help us make sure the change don't break any core functionality.

**Comment by riccardo-salamanna** [comment]
Gotcha i'll try to get it sorted asap

**Comment by riccardo-salamanna** [comment]
Hi @Arman-Keyoumarsi! thanks for your feedback. I added a default value and now both tests seems successful:
smoke test
`Plan: 1 to add, 0 to change, 0 to destroy.`
I also added the required sanity tests and all the outputs were successful. I tested multiple combination of values, from the stardard (high-normal-low)  to the custom with numbered values
`    cpu_share_level    = "custom"
    cpu_share_count    = null
    memory_share_level = "custom"
    memory_share_count = 8192
    io_share_level     = ["high"]
    io_share_count     = null
    io_reservation     = ["3000"]
`

Let me know if you need anything else

**Comment by Arman-Keyoumarsi** [comment]
Thanks @riccardo-salamanna everything checks out

**Pull request merged**
