### PR TITLE
Add disk datastore options

### PR DESCRIPTION
**Pull request by SamyCoenen**
Adds disk datastore option for template disks and additional data disks

Fixes https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/issues/16

### CODE REVIEW

**Comment by SamyCoenen** [comment]
output:
```
      + disk {                                                                                    
          + attach           = false                                                              
          + datastore_id     = "datastore-12"                                                     
          + device_address   = (known after apply)                                                
          + disk_mode        = "persistent"                                                                                                                                                                                                       
          + disk_sharing     = "sharingNone"                                                      
          + eagerly_scrub    = false                                                                                           
          + io_limit         = -1                                                                                                                                                                                                                                                                                                                                         
          + io_reservation   = 0                                                                              
          + io_share_count   = 0                                                                              
          + io_share_level   = "normal"                                                                       
          + keep_on_remove   = false                                                                          
          + key              = 0                                                                              
          + label            = "disk0"                                                                        
          + path             = (known after apply)                                                            
          + size             = 20                                                                             
          + thin_provisioned = true                                                                           
          + unit_number      = 0                                                                              
          + uuid             = (known after apply)                                                            
          + write_through    = false                                                                          
        }                                                                                                     
      + disk {                                                                                                
          + attach           = false                                                                          
          + datastore_id     = "datastore-12"                                                                 
          + device_address   = (known after apply)                                                            
          + disk_mode        = "persistent"                                                                   
          + disk_sharing     = "sharingNone"                                                                  
          + eagerly_scrub    = false                                                                          
          + io_limit         = -1                                                                             
          + io_reservation   = 0                                                                              
          + io_share_count   = 0                                                                              
          + io_share_level   = "normal"                                                                       
          + keep_on_remove   = false                                                                          
          + key              = 0                                                                              
          + label            = "disk1"                                                                        
          + path             = (known after apply)                                                            
          + size             = 30                                                                             
          + thin_provisioned = true                                                                           
          + unit_number      = 1                                                                              
          + uuid             = (known after apply)                                                            
          + write_through    = false                                                                          
        }                                                                                                     
      + disk {                                                                                                
          + attach           = false                                                                          
          + datastore_id     = "datastore-4235"                                                               
          + device_address   = (known after apply)                                                            
          + disk_mode        = "persistent"                                                                   
          + disk_sharing     = "sharingNone"                                                                  
          + eagerly_scrub    = false                                                                          
          + io_limit         = -1                                                                             
          + io_reservation   = 0                                                                              
          + io_share_count   = 0                                                                              
          + io_share_level   = "normal"                                                                       
          + keep_on_remove   = false                                                                          
          + key              = 0                                                                              
          + label            = "disk2"                                                                        
          + path             = (known after apply)                                                            
          + size             = 20                                                                             
          + thin_provisioned = true                                                                           
          + unit_number      = 2                                                                              
          + uuid             = (known after apply)                                                            
          + write_through    = false                                                                          
        }
```

**Comment by Arman-Keyoumarsi** [comment]
Hey Sammy, 

Thanks for the pull request, Looks good.

**Comment by Arman-Keyoumarsi** [comment]
Hello Samy, 

I have reverted the merge since there are unresolved issue. 

regards,

**Comment by SamyCoenen** [comment]
@Arman-Keyoumarsi I understand, I have updated the code and tested it with and without disk_datastore(s) and made a new pull request.

**Pull request merged**
